<?php

declare(strict_types=1);

require __DIR__ . '/../src/bootstrap.php';
require __DIR__ . '/../src/Database.php';

$root = dirname(__DIR__);
$envPath = $root . '/.env';
$dataDir = $root . '/data';
$dbPath = $dataDir . '/marketing.sqlite';

$defaults = [
    'BUSINESS_NAME' => 'My Small Business',
    'BUSINESS_INDUSTRY' => 'Local services',
    'TIMEZONE' => 'America/New_York',
    'AI_PROVIDER' => 'openai',
    'AI_MODEL' => 'gpt-4.1-mini',
    'OPENAI_API_KEY' => '',
    'OPENAI_BASE_URL' => 'https://api.openai.com/v1',
    'ANTHROPIC_API_KEY' => '',
    'ANTHROPIC_MODEL' => 'claude-sonnet-4-20250514',
    'GEMINI_API_KEY' => '',
    'GEMINI_MODEL' => 'gemini-2.5-flash',
];

$values = $defaults;
if (is_file($envPath)) {
    foreach (file($envPath, FILE_IGNORE_NEW_LINES | FILE_SKIP_EMPTY_LINES) as $line) {
        if (str_starts_with(trim($line), '#') || !str_contains($line, '=')) {
            continue;
        }
        [$key, $value] = array_map('trim', explode('=', $line, 2));
        if (array_key_exists($key, $values)) {
            $values[$key] = $value;
        }
    }
}

$status = [];
$errors = [];
$success = false;

if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    foreach (array_keys($defaults) as $key) {
        $values[$key] = trim((string)($_POST[$key] ?? ''));
    }

    foreach (['BUSINESS_NAME', 'BUSINESS_INDUSTRY', 'TIMEZONE', 'AI_PROVIDER'] as $required) {
        if ($values[$required] === '') {
            $errors[] = "{$required} is required.";
        }
    }

    if (!in_array($values['AI_PROVIDER'], ['openai', 'anthropic', 'gemini'], true)) {
        $errors[] = 'AI_PROVIDER must be openai, anthropic, or gemini.';
    }

    if ($errors === []) {
        if (!is_dir($dataDir) && !mkdir($dataDir, 0777, true) && !is_dir($dataDir)) {
            $errors[] = 'Unable to create the data directory. Check filesystem permissions.';
        }

        if ($errors === []) {
            $envLines = [
                '# Generated by web installer (' . gmdate(DATE_ATOM) . ')',
            ];

            foreach ($values as $key => $value) {
                $envLines[] = sprintf('%s=%s', $key, str_replace(["\r", "\n"], ' ', $value));
            }

            $written = file_put_contents($envPath, implode(PHP_EOL, $envLines) . PHP_EOL);
            if ($written === false) {
                $errors[] = 'Unable to write .env file. Check directory permissions.';
            } else {
                try {
                    new Database($dbPath);
                    $status[] = 'Database initialized successfully.';
                    $success = true;
                } catch (Throwable $exception) {
                    $errors[] = 'Database initialization failed: ' . $exception->getMessage();
                }
            }
        }
    }
}

function esc(string $value): string
{
    return htmlspecialchars($value, ENT_QUOTES, 'UTF-8');
}

$installed = is_file($envPath) && is_file($dbPath);
?>
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width,initial-scale=1" />
  <title>Marketing Suite Installer</title>
  <style>
    body { font-family: Inter, Arial, sans-serif; background: #f6f8fb; margin: 0; color: #111827; }
    .wrap { max-width: 760px; margin: 2rem auto; background: #fff; border-radius: 14px; box-shadow: 0 8px 30px rgba(0,0,0,0.08); padding: 1.2rem 1.4rem; }
    h1 { margin: 0.2rem 0 0.5rem; font-size: 1.5rem; }
    p { color: #4b5563; }
    .grid { display: grid; grid-template-columns: 1fr 1fr; gap: 0.8rem; }
    label { display: block; font-size: 0.85rem; font-weight: 600; margin: 0.6rem 0 0.2rem; }
    input, select { width: 100%; box-sizing: border-box; padding: 0.55rem; border: 1px solid #d1d5db; border-radius: 8px; }
    .full { grid-column: 1 / -1; }
    .msg { padding: 0.7rem 0.9rem; border-radius: 9px; margin: 0.8rem 0; }
    .ok { background: #ecfdf5; color: #065f46; }
    .err { background: #fef2f2; color: #991b1b; }
    .warn { background: #fffbeb; color: #92400e; }
    button { margin-top: 1rem; background: #2563eb; color: #fff; border: none; padding: 0.7rem 1rem; border-radius: 8px; cursor: pointer; font-weight: 600; }
    code { background: #f3f4f6; padding: 0.15rem 0.3rem; border-radius: 4px; }
    ul { margin: 0; padding-left: 1.2rem; }
  </style>
</head>
<body>
<div class="wrap">
  <h1>Marketing Suite Web Installer</h1>
  <p>Use this page once to create <code>.env</code>, initialize SQLite, and start the app without shell access.</p>

  <?php if ($installed && !$success): ?>
    <div class="msg warn">An existing installation was detected. Saving this form will update <code>.env</code> and re-run database migrations.</div>
  <?php endif; ?>

  <?php if ($errors !== []): ?>
    <div class="msg err">
      <strong>Installer errors:</strong>
      <ul>
        <?php foreach ($errors as $error): ?>
          <li><?= esc($error) ?></li>
        <?php endforeach; ?>
      </ul>
    </div>
  <?php endif; ?>

  <?php if ($success): ?>
    <div class="msg ok">
      <strong>Installation complete.</strong>
      <ul>
        <?php foreach ($status as $item): ?>
          <li><?= esc($item) ?></li>
        <?php endforeach; ?>
      </ul>
      <p style="margin-top:0.6rem;">You can now open <a href="/">the app</a>. For security, remove or restrict access to <code>install.php</code> after setup.</p>
    </div>
  <?php endif; ?>

  <form method="post">
    <div class="grid">
      <div>
        <label for="BUSINESS_NAME">Business name</label>
        <input id="BUSINESS_NAME" name="BUSINESS_NAME" value="<?= esc($values['BUSINESS_NAME']) ?>" required />
      </div>
      <div>
        <label for="BUSINESS_INDUSTRY">Industry</label>
        <input id="BUSINESS_INDUSTRY" name="BUSINESS_INDUSTRY" value="<?= esc($values['BUSINESS_INDUSTRY']) ?>" required />
      </div>
      <div>
        <label for="TIMEZONE">Timezone</label>
        <input id="TIMEZONE" name="TIMEZONE" value="<?= esc($values['TIMEZONE']) ?>" required />
      </div>
      <div>
        <label for="AI_PROVIDER">AI provider</label>
        <select id="AI_PROVIDER" name="AI_PROVIDER">
          <?php foreach (['openai', 'anthropic', 'gemini'] as $provider): ?>
            <option value="<?= esc($provider) ?>" <?= $values['AI_PROVIDER'] === $provider ? 'selected' : '' ?>><?= esc($provider) ?></option>
          <?php endforeach; ?>
        </select>
      </div>
      <div>
        <label for="AI_MODEL">OpenAI model alias</label>
        <input id="AI_MODEL" name="AI_MODEL" value="<?= esc($values['AI_MODEL']) ?>" />
      </div>
      <div>
        <label for="OPENAI_BASE_URL">OpenAI base URL</label>
        <input id="OPENAI_BASE_URL" name="OPENAI_BASE_URL" value="<?= esc($values['OPENAI_BASE_URL']) ?>" />
      </div>
      <div class="full">
        <label for="OPENAI_API_KEY">OpenAI API key (optional)</label>
        <input id="OPENAI_API_KEY" name="OPENAI_API_KEY" value="<?= esc($values['OPENAI_API_KEY']) ?>" />
      </div>
      <div class="full">
        <label for="ANTHROPIC_API_KEY">Anthropic API key (optional)</label>
        <input id="ANTHROPIC_API_KEY" name="ANTHROPIC_API_KEY" value="<?= esc($values['ANTHROPIC_API_KEY']) ?>" />
      </div>
      <div>
        <label for="ANTHROPIC_MODEL">Anthropic model</label>
        <input id="ANTHROPIC_MODEL" name="ANTHROPIC_MODEL" value="<?= esc($values['ANTHROPIC_MODEL']) ?>" />
      </div>
      <div>
        <label for="GEMINI_MODEL">Gemini model</label>
        <input id="GEMINI_MODEL" name="GEMINI_MODEL" value="<?= esc($values['GEMINI_MODEL']) ?>" />
      </div>
      <div class="full">
        <label for="GEMINI_API_KEY">Gemini API key (optional)</label>
        <input id="GEMINI_API_KEY" name="GEMINI_API_KEY" value="<?= esc($values['GEMINI_API_KEY']) ?>" />
      </div>
    </div>

    <button type="submit">Install / Update</button>
  </form>
</div>
</body>
</html>
